# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8543fc3bf99afd52189cd56a0fe80f78c36edfb3ebb7b9137c3b768c03e571fb3e71dac17bfe95a0b4239f38787b7a7d1654adde69c4bc4164049d64745a6212

test:
  secret_key_base: b93dc3eab8187c6c7c379f06c254bcfca41cf656a132dca0d52565135ac00e47866d601fc185b01d004da88c5f8ff6a35f4119a170d146e0bd0be57fa6f0f2d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
